### ISSUE TITLE
Finish and merge feature branch on appendix

### ISSUE THREAD

**Issue by deprecated** [deprecated/bowshock-shape#38]
Jorge has a branch called *appendix* that has not been merged into the trunk.  I think it has some material on the parabola case.  We need to deal with it.

**Comment by Lxndrs** [comment]
Other material to include into appendix

1. Derivation of Radius of Curvature in the thin shell model
2. Derivation of R90 in the thin shell model?

Currently working in 1.

**Comment by Lxndrs** [comment]
Finished point 2.
