### ISSUE TITLE
Cosmetic improvements to figures

### ISSUE THREAD

**Issue by deprecated** [deprecated/bowshock-shape#40]
- Figure 5
   - [x] Use `whitegrid` style
   - [x] Make full column width in latex file
   - [x] Larger text (see Fig 6)
   - [x] Use `bbox` to put white translucent boxes behind labels
- Figure 7
   - [ ] Reduce range in A and in y limit (up to 5 maybe)
- Figure 8
   - [x] Use `whitegrid` style
   - [x] Larger text
- Figure 10
  - [x] Remove most of the text in boxes (keep just xi and beta)

**Comment by Lxndrs** [comment]
Changes in figure 5 and 8 already commited.

**Comment by deprecated** [comment]
Figure 8 still needs the text to be bigger.  I suggest simply reducing the figure size slightly.

**Comment by deprecated** [comment]
#44 may end up replacing/eliminating Fig 7

**Comment by deprecated** [comment]
Figure 7 now removed, so all tasks in this issue are done
