### ISSUE TITLE
Add graph of R_0' / D' versus inclination for different conics

### ISSUE THREAD

**Issue by deprecated** [deprecated/bowshock-shape#46]
Since R_c' is now going to get paired off with T_c' (see #43), it might be clearer to show (R_0' / D') / (R_0 / D) versus i.  This would be instead of the current Fig 7. 

We could also plot ~R_c' versus i.

**Comment by Lxndrs** [comment]
[q'/q vs inc graph](https://github.com/deprecated/bowshock-shape/blob/master/papers/Paper1/figs/qprime-vs-inc.pdf)

**Comment by deprecated** [comment]
I hadn't noticed your graphs - sorry!

In the end I decided to show R0'/R0 and D'/D separately.
